# DESCRIPTION
#    This script is used on fetch_logs.yml file and its purpose is to fetch some data from exim logs. Remember to install RSYNC on ansible server before running script.
#
# TASKS
#    1. Create file with list of services which failed to start.
#    2. Copy created file from client machine.
#    3. Remove created file from client machine.
#
# VERSION
#       1.0 - Initial version
#       1.1 - updated description and added numbers to tasks
#       
# CODE
---
- name: Fetch logs from server
  hosts: <ansible_target>
  become: true
  gather_facts: false
  tasks:
    - name: 1. Create file with service names that failed to start
      shell: |
        touch failed_services
        systemctl list-units | grep -i failed > failed_services
        if [ ! -s "failed_services" ]; then echo "There is no failed services on that machine" > failed_services ; fi

    - name: 2. Fetch file from client machine
      ansible.builtin.fetch:
        src: failed_services
        dest: /home/ansible

    #- name: Remove created file
    #  shell: rm failed_services  

    - name: 3. Remove created file
      ansible.builtin.file:
        path: failed_services
        state: absent