# DESCRIPTION
#    Playbook for installing package for debian based system.
#
# TASKS
#    1. Install package on client machine
#
# VERSION
#       1.0 - Initial version
#       1.1 - Added description
#       
# CODE
---
- name: Install package
  hosts: <ansible_target>
  become: true
  gather_facts: false
  tasks:
    - name: Instalation
      apt:
        name: <package name>
        state: latest # avaiable options: latest, absent, present

