# DESCRIPTION
#    Playbook for removing package from debian based system.
#
# TASKS
#    1. Remove package from client machine.
#
# VERSION
#       1.0 - Initial version
#       1.1 - Added description
#       
# CODE
---
- name: Remove package
  hosts: <ansible_target>
  become: true
  gather_facts: false
  tasks:
    - name: Removing
      apt:
        name: <package name>
        state: absent

